feat: 22878 activate physical card
pasyukevich/Expensify-app pull request #3
Opened 2023-09-25 11:38 UTC by MrMuzyk

### Details
Draft PR for [22878](https://github.com/Expensify/App/issues/22878)

### Fixed Issues

$ 
PROPOSAL: 

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected accor [...]

2023-09-25 11:52 UTC, rezkiy37 commented on src/components/MagicCodeInput.js
> +    disableKeyboard: PropTypes.bool,
We prefer `isSomething` or `shouldSomething`, when a value is boolean. Also, `disableKeyboard` sounds like a function to do disable.
```suggestion
    isKeyboardDisable: PropTypes.bool,
```

2023-09-25 11:54 UTC, rezkiy37 commented on src/components/MagicCodeInput.js
> +        // + the onChangeText and onKeyPress as the dependencies because we only want to run this when lastPressedDigit changes.
Can we wrap `onChangeText` into a `useCallback` to memorise the function?

2023-09-25 11:58 UTC, rezkiy37 commented on src/pages/settings/Wallet/ActivateCardPage.js
> +        }),
1. Can we expect when there is a shape of cards, we always have `isLoading`? 
2. Can we extend a card object?

```suggestion
        isLoading: PropTypes.bool.isRequired,
        [PropTypes.string]: PropTypes.objectOf({
            ...assignedCardPropTypes,   
            errors: PropTypes.object.isRequired,
        }),
```

2023-09-25 11:59 UTC, rezkiy37 commented on src/pages/settings/Wallet/ActivateCardPage.js
> +            onBackButtonPress={() => Navigation.goBack()}
```suggestion
            onBackButtonPress={Navigation.goBack}
```

2023-09-25 12:00 UTC, rezkiy37 commented on src/pages/settings/Wallet/ActivateCardPage.js
> +                {DeviceCapabilities.canUseTouchScreen() ? <BigNumberPad numberPressed={updateLastPressedDigit} /> : null}
If `canUseTouchScreen` always returns a boolean value, we can simplify a condition.
```suggestion
                {DeviceCapabilities.canUseTouchScreen() && <BigNumberPad numberPressed={updateLastPressedDigit} />}
```

2023-09-25 12:01 UTC, rezkiy37 commented on src/pages/settings/Wallet/ExpensifyCardPage.js
> +    cardList: PropTypes.shape({
This value is being used a few times. Let's create a file with a prop types for `cardList` to re-use it across files.

2023-09-25 12:02 UTC, rezkiy37 commented on src/pages/settings/Wallet/ExpensifyCardPage.js
> +                    {physicalCard.state === CARD_NOT_ACTIVATED_STATE ? (
```suggestion
                    {physicalCard.state === CARD_NOT_ACTIVATED_STATE && (
```

2023-09-25 12:02 UTC, rezkiy37 commented on src/pages/settings/Wallet/ExpensifyCardPage.js
> +                    ) : null}
```suggestion
                    )}
```

2023-09-25 12:02 UTC, rezkiy37 reviewed
Left comments.

2023-09-25 12:05 UTC, MrMuzyk commented on src/components/MagicCodeInput.js
> +    disableKeyboard: PropTypes.bool,
This is literally what `TextInput` component widely used in the app expects. Prop name is 1:1 the same

2023-09-25 12:06 UTC, adhorodyski commented on src/pages/settings/Wallet/ActivateCardPage.js
> +                {DeviceCapabilities.canUseTouchScreen() ? <BigNumberPad numberPressed={updateLastPressedDigit} /> : null}
Honestly I'd default to a ternary - the underlying implementation might change and it will affect this component causing a regression.

2023-09-25 12:07 UTC, adhorodyski commented on src/pages/settings/Wallet/ExpensifyCardPage.js
> +                    {physicalCard.state === CARD_NOT_ACTIVATED_STATE ? (
@rezkiy37 I often like to refer to this Kent's article https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx

2023-09-25 12:07 UTC, rezkiy37 commented on src/components/MagicCodeInput.js
> +    disableKeyboard: PropTypes.bool,
Yeah, I see. I just remember - https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#boolean-variables-and-props. This case could be an exception.

2023-09-25 12:10 UTC, MrMuzyk commented on src/pages/settings/Wallet/ActivateCardPage.js
> +        }),
![image](https://github.com/pasyukevich/Expensify-app/assets/23487612/4eea8180-bb85-4e2c-83c9-649fb0ef8f0d)

This is what ill be expecting in onyx. Errors are going to be said on the object under the cardID key. Not sure if there is a nicer way to shape props in such scenario.

As for isLoading, I agree

2023-09-25 12:11 UTC, rezkiy37 commented on src/pages/settings/Wallet/ActivateCardPage.js
> +                {DeviceCapabilities.canUseTouchScreen() ? <BigNumberPad numberPressed={updateLastPressedDigit} /> : null}
It is already migrated to TS and has a [strict type](https://github.com/Expensify/App/blob/main/src/libs/DeviceCapabilities/canUseTouchScreen/types.ts). So, we can expect that it returns boolean forever. However, it is not something critical. Up to you.

2023-09-25 12:13 UTC, MrMuzyk commented on src/components/MagicCodeInput.js
> +    disableKeyboard: PropTypes.bool,
k, ill change it

2023-09-25 12:15 UTC, rezkiy37 commented on src/pages/settings/Wallet/ExpensifyCardPage.js
> +                    {physicalCard.state === CARD_NOT_ACTIVATED_STATE ? (
I got you. Also, makes sense.

2023-09-25 12:16 UTC, MrMuzyk commented on src/pages/settings/Wallet/ExpensifyCardPage.js
> +                    {physicalCard.state === CARD_NOT_ACTIVATED_STATE ? (
I guess its accepted here, there is even a point in the PR checklist - ` I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. myBool && <MyComponent />.`

2023-09-25 12:17 UTC, rezkiy37 commented on src/pages/settings/Wallet/ActivateCardPage.js
> +        }),
Ah, I see. Therefore, no sense to extend a card object with errors.

2023-09-25 12:18 UTC, gedu commented on src/components/MagicCodeInput.js
> +        // + the onChangeText and onKeyPress as the dependencies because we only want to run this when lastPressedDigit changes.
Given that `onChangeText` isn't being use into any dependency array, there is no need to wrap it into a `useCallback`

2023-09-25 12:20 UTC, rezkiy37 commented on src/components/MagicCodeInput.js
> +        // + the onChangeText and onKeyPress as the dependencies because we only want to run this when lastPressedDigit changes.
@gedu, `onChangeText` is being used in `useEffect` and explicitly skipped in a deps. array of this `useEffect`.

2023-09-25 12:30 UTC, gedu commented on src/pages/settings/Wallet/ActivateCardPage.js
> +    cardList,
It is a list or an object? I think the name is confusing

2023-09-25 12:50 UTC, BeeMargarida commented on src/libs/actions/CardSettings.js
> +
unnecessary new line

2023-09-25 12:50 UTC, BeeMargarida commented on src/pages/settings/Wallet/ActivateCardPage.js
> +    route: PropTypes.shape({
I would move route as the first prop, since it's not an Onyx prop. It seems like this is the standard.

2023-09-25 12:50 UTC, BeeMargarida commented on src/pages/settings/Wallet/ActivateCardPage.js
> +const CARD_ACTIVATED_STATE = 3;
Can't this be moved to CONST? The same with the const in ExpensifyCardPage.
I think it would be useful to have all the states under a readable const, grouped by ACTIVE_CARD or something like that. Like the `STATE_NUM` const of a report.

2023-09-25 12:57 UTC, MrMuzyk commented on src/pages/settings/Wallet/ActivateCardPage.js
> +    cardList,
I wasnt the one who created this onyxkey, it was already in the codebase added by some1 else

2023-09-25 12:57 UTC, MrMuzyk commented on src/libs/actions/CardSettings.js
> +
shouldnt it be covered by prettier?

2023-09-25 13:10 UTC, gedu commented on src/components/MagicCodeInput.js
> +        // + the onChangeText and onKeyPress as the dependencies because we only want to run this when lastPressedDigit changes.
as the comment said `only want to run this when lastPressedDigit changes`, so if the function isn't being used in the dependency array, there is no need to use `useCallback`, because the hook `useEffect` isn't checking if the `onChangeText` change the reference.

2023-09-25 13:14 UTC, rezkiy37 commented on src/components/MagicCodeInput.js
> +        // + the onChangeText and onKeyPress as the dependencies because we only want to run this when lastPressedDigit changes.
Yeah, makes sense. I just thought that we can a full deps. array. Forget.

2023-09-25 13:27 UTC, BeeMargarida commented on src/libs/actions/CardSettings.js
> +
It should, but I think it's not

2023-09-26 07:39 UTC, MrMuzyk commented on src/pages/settings/Wallet/ActivateCardPage.js
> +    route: PropTypes.shape({
After looking into it I dont think its a standard. ExpensifyCardPage just got merged and it doesnt follow this practice. Neither do plenty of other components

2023-09-26 09:40 UTC, MrMuzyk commented on src/pages/settings/Wallet/ActivateCardPage.js
> +        }),
I had to re-do the props completely because it turns out that the structure I was expecting was incorrect. Also after a second thought, isLoading cant be required prop. Its not gonna be there in the begining, its added after 1st API call

2023-09-26 09:50 UTC, rezkiy37 commented on src/pages/settings/Wallet/ActivateCardPage.js
> +        }),
Thank you for letting me know 🙂

2023-09-26 09:53 UTC, rezkiy37 approved these changes
LGTM.

2023-09-26 11:04 UTC, BeeMargarida approved these changes

2023-09-26 12:09 UTC, pasyukevich requested changes

2023-09-26 12:09 UTC, pasyukevich commented on src/types/onyx/CardList.ts
> +    physical: Card;
are you sure that we will have such keys? 

As far as I know, we will use here card ID as a key

2023-09-26 12:09 UTC, pasyukevich commented on src/pages/settings/Wallet/ActivateCardPage.js
> +        if (!cardList.isLoading && lodashGet(cardList, 'physical.state', 0) === CARD_ACTIVATED_STATE) {
pls use  `CardUtils.getDomainCards(cardList)[domain];`

we don't need whole list here, only the domain

2023-09-26 12:09 UTC, pasyukevich commented on src/pages/settings/Wallet/ActivateCardPage.js
> +        if (!cardList.isLoading && lodashGet(cardList, 'physical.state', 0) === CARD_ACTIVATED_STATE) {
https://docs.google.com/document/d/1rFxJ78vz5On6zSWzYa51B9v-tyLdC5pUsBeLOLig0t4/edit#heading=h.s5rzg79l078b

2023-09-26 12:09 UTC, pasyukevich commented on src/pages/settings/Wallet/ActivateCardPage.js
> +        if (cardList.isLoading) {
Can we put isLoading state to the related card / domain ?

2023-09-26 12:09 UTC, pasyukevich commented on src/ONYXKEYS.ts
> +    [ONYXKEYS.CARD_LIST]: OnyxTypes.CardList;
I think we need to have here previous structure and apply changes to the `Card` entity itself

2023-09-26 12:09 UTC, pasyukevich commented on src/libs/actions/CardSettings.js
> +function activatePhysicalExpensifyCard(lastFourDigits, cardID) {
I'm a bit confused with namings in declaring and calling 

Here I see lastFourDigits argument, but in the call we have activateCardCode.

What naming is describing this value?

2023-09-26 12:09 UTC, pasyukevich commented on src/pages/settings/Wallet/ExpensifyCardPage.js
> +        [PropTypes.number]: PropTypes.objectOf(assignedCardPropTypes),
In Onyx we will have cardList object with  key value: 

```
{
   'string' : assignedCardPropTypes,
   'anotherstring' : assignedCardPropTypes,
   ....
}
```

Here you updated to such structure: 

```
{
   isLoading: PropTypes.bool,
   23452345: {
   'string' : assignedCardPropTypes,
   'anotherstring' : assignedCardPropTypes,
   ....
   }
}
```

2023-09-26 12:09 UTC, pasyukevich commented on src/types/onyx/CardList.ts
> +type CardList = Record<number, Card> & {
We don't have number key in current structure from BE

2023-09-26 12:09 UTC, pasyukevich commented on src/types/onyx/CardList.ts
> +    isLoading: boolean;
Can we move this to the Card itself?

2023-09-26 13:11 UTC, pasyukevich commented on src/pages/settings/Wallet/ExpensifyCardPage.js
> +                    {physicalCard.state === CONST.CARD_STATE.NOT_ACTIVATED && (
Looks like this part is not workable anymore since we do not have `physicalCard` variable here

2023-09-26 13:13 UTC, pasyukevich commented on src/libs/actions/CardSettings.js
I guess CardSettings is not suitable here, since activation is not part of card settings 

What do you think about  CardActions.js ?

2023-09-26 13:47 UTC, pasyukevich commented on src/libs/actions/CardSettings.js
Or even simply Card.js

2023-09-27 11:34 UTC, pasyukevich commented on src/pages/settings/Wallet/ExpensifyCardPage.js
> +    cardList: PropTypes.shape({
In this case we can have just `cardList: PropTypes.objectOf(assignedCardPropTypes),`

2023-09-27 11:34 UTC, pasyukevich commented on src/pages/settings/Wallet/ActivateCardPage.js
> +    cardList: PropTypes.shape({
In this case we can have just `cardList: PropTypes.objectOf(assignedCardPropTypes),`

2023-09-27 11:35 UTC, pasyukevich approved these changes

2023-10-18 13:14 UTC, closed without merging